name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" OfficeFormExample/OfficeFormExample.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file OfficeFormExample/Dockerfile --tag form-office:${{ env.VERSION }}
